#source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target 'pzhixin' do
  pod 'AFNetworking', '~>3.2.0'
  pod 'MJRefresh', '~>3.3.1'
  pod 'MBProgressHUD'
  pod 'Reachability'
  pod 'IQKeyboardManager'
  pod 'FMDB'
  pod 'GTMBase64'
  pod 'WechatOpenSDK', '~>1.8.6'
  pod 'LTNavigationBar'
  pod 'SDCycleScrollView'
  pod 'YYText'
  pod 'YYImage'
  pod 'ZFPlayer'
  pod 'ZFPlayer/AVPlayer'
  pod 'ZFPlayer/ControlView'
  pod 'LBXScan/LBXNative','~> 2.3'
  pod 'LBXScan/LBXZXing','~> 2.3'
  pod 'LBXScan/LBXZBar','~> 2.3'
  pod 'LBXScan/UI','~> 2.3'
  pod 'YYModel'
  pod 'CRBoxInputView'
  pod 'UICollectionViewLeftAlignedLayout'
  pod 'JPush', '~> 3.2.6'
  pod 'Bugly'
  pod 'ReactiveObjC'
  pod 'ZLPhotoBrowser', '~> 3.1.2'
  pod 'lottie-ios', '~> 2.5.3'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'JXCategoryView'
  pod 'AlibcTradeSDK','~> 4.0.0.8'
  pod 'AliAuthSDK','~> 2.0.0.3'
  pod 'mtopSDK','~> 3.0.0.4'
  pod 'securityGuard','~> 5.4.173'
  pod 'AliLinkPartnerSDK','~> 4.0.0.24'
  pod 'BCUserTrack','~> 5.2.0.11-appkeys'
  pod 'UTDID','~> 1.1.0.16'
  pod 'iCarousel'
  pod 'DZNEmptyDataSet'
  pod 'BlocksKit'
  pod 'SDWebImageWebPCoder'
  pod 'YYImage/WebP'
  pod 'FDFullscreenPopGesture'
  pod 'TYPagerController'
  pod 'SVProgressHUD'
  pod 'dsBridge'
  pod 'UICountingLabel'
  pod 'MGJRouter'
  pod 'TYCyclePagerView'
  pod 'GDTMobSDK'
  pod 'Bytedance-UnionAD'
  pod 'YBImageBrowser'
end
